
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package ve.edu.unet;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GTEQ = 17;
  public static final int OVER = 22;
  public static final int LTEQ = 18;
  public static final int LPAREN = 23;
  public static final int SEMI = 25;
  public static final int REPEAT = 6;
  public static final int INT = 28;
  public static final int FOR = 33;
  public static final int MINUS = 20;
  public static final int WRITE = 9;
  public static final int RPAREN = 24;
  public static final int NOT = 32;
  public static final int AND = 30;
  public static final int LT = 15;
  public static final int OR = 31;
  public static final int BOOL = 29;
  public static final int UNTIL = 7;
  public static final int NUM = 11;
  public static final int PLUS = 19;
  public static final int ASSIGN = 12;
  public static final int IF = 2;
  public static final int ID = 10;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int MOD = 27;
  public static final int NEQ = 14;
  public static final int EQ = 13;
  public static final int TIMES = 21;
  public static final int COLON = 26;
  public static final int ELSE = 4;
  public static final int READ = 8;
  public static final int WHILE = 34;
  public static final int THEN = 3;
  public static final int END = 5;
  public static final int GT = 16;
  public static final int DO = 35;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "THEN",
  "ELSE",
  "END",
  "REPEAT",
  "UNTIL",
  "READ",
  "WRITE",
  "ID",
  "NUM",
  "ASSIGN",
  "EQ",
  "NEQ",
  "LT",
  "GT",
  "GTEQ",
  "LTEQ",
  "PLUS",
  "MINUS",
  "TIMES",
  "OVER",
  "LPAREN",
  "RPAREN",
  "SEMI",
  "COLON",
  "MOD",
  "INT",
  "BOOL",
  "AND",
  "OR",
  "NOT",
  "FOR",
  "WHILE",
  "DO"
  };
}

